apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-transport-layer-pvc
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: dtl
