apiVersion: v1
kind: PersistentVolume
metadata:
  name: please-input
  labels:
    app: please-input
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-01e7d335ba8df7d82
