apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: l2geth-pvc
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: l2geth