apiVersion: v1
kind: ConfigMap
metadata:
  name: relayer
data:
  MESSAGE_RELAYER__L1_RPC_PROVIDER: 'http://l1chain-svc:8545'
  MESSAGE_RELAYER__L2_RPC_PROVIDER: 'http://l2geth-svc:8545'
  RETRIES: '60'

  URL: 'http://deployer-svc:8081/addresses.json'
