apiVersion: v1
kind: ConfigMap
metadata:
  name: deployer
data:
  CONTRACTS_RPC_URL: 'http://l1chain-svc:8545'
  CONTRACTS_DEPLOYER_KEY: 'ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
  CONTRACTS_TARGET_NETWORK: local
