apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployer
spec:
  selector:
    matchLabels:
      app: deployer
  replicas: 1
  template:
    metadata:
      labels:
        app: deployer
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: deployer
          image: onthertech/titan-deployer
          imagePullPolicy: IfNotPresent
          command: ['./deployer.sh']
          restartPolicy: Never
          ports:
            - containerPort: 8081
              protocol: TCP
          resources: {}
          envFrom:
            - configMapRef:
                name: deployer
