definitions:
  model.Network:
    properties:
      contract_address_url:
        type: string
      created_at:
        type: integer
      id:
        type: integer
      state_dump_url:
        type: string
      status:
        type: boolean
      updated_at:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: Titond-backend application
  title: Titond
  version: "1.0"
paths:
  /api/networks:
    post:
      description: Create a new network
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Network'
        "500":
          description: Internal Server Error
      summary: CreateNetwork
  /api/networks/{id}:
    delete:
      description: Delete a network by id
      parameters:
      - description: Network ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: DeleteNetwork
swagger: "2.0"
