name: Tokamak Titond Publish (Nightly Version)

on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get versions
        id: extractver
        run: echo "GITSHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: onthertech/titan-titond-backend:nightly,onthertech/titan-titond-backend:nightly-${{ steps.extractver.outputs.GITSHA }}
