name: Run unit test
on: push

jobs:
  image:
    name: Check swagger docs for titond-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check swagger
        run: |
          CGO_ENABLED=0 GOOS=linux go build -o ./build/bin/titond ./cmd/titond/main.go
          ./build/bin/titond check-swagger
