name: Check swagger
on: push

jobs:
  image:
    name: Check swagger docs for titond-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check swagger
        run: |
          go run ./cmd/titond/main.go check-swagger
