name: Run unit test
on: push

jobs:
    image:
        name: Run UT for titond-backend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Run test
              run: |
                  MODE=test go test -v ./...
